### PR TITLE
executor::Spawn: add an optional park timeout for blocking methods

### PR DESCRIPTION
**Pull request by abonander**
This is useful for futures which want to be polled even without being able to move forward; otherwise, it would be necessary to spawn an extra thread to send notifications to the future. For my use-case, I want to animate a "Working..."  message on stdout while waiting for the completion of a future on a background thread, and polling on regular intervals seems to be the easiest way to go about this.

Since `thread::park()` can wake spuriously anyways, this doesn't seem to break any guarantees of the current API.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! This wasn't quite how I envisioned timeout support but this seems like, but it seems nifty! 

I was thinking that when a timeout elapsed it'd be returned to the user instead of simply re-polling the future so the timeout could be acted on, but maybe that could be a suite of extra methods? I kinda like the ability to set the timeout globally for a `Spawn` and then other operations just fall out without extra apis.

I'm curious, do you think there's much of a use case for acting externally in the event of a timeout?

**Comment by carllerche** [comment]
I would prefer keeping the timeout out of the struct. `Spawn` is a fundamental construct that and **must** be used by all schedulers. It would be better to keep it as small as possible IMO and provide an additional abstraction for convenience.

If there is a way to execute a future w/o using `Spawn`, let me know, because I think it is the only way to correctly setup the necessary thread locals.

**Comment by abonander** [comment]
@carllerche there's not any additional cost to code that doesn't use timeouts so I don't see the issue of maintaining it in `Spawn`, unless you're really concerned about the additional size an `Option<Duration>` adds. 

Re: handling externally, I don't know of any use cases specifically but re-polling after the timeout is simple enough so it makes more sense. However, this should be in separate methods which can have return types to signify the timeout; the `Poll` result type works as the `NotReady` value could signify that the operation timed out. If we're adding separate methods then storing the timeout in `Spawn` becomes less obligatory.

**Comment by carllerche** [comment]
I'm definitely concerned about the `Option<Duration>` storage space. A cache line is 64 bytes and this adds an extra 16, aka takes up 25% of the cache line for something that will be rarely used.

**Comment by abonander** [comment]
So are we thinking a more traditional approach, i.e. adding methods that take a timeout as a parameter? I'm thinking:

* `wait_future_timeout`
* `wait_stream_timeout`
* `wait_send_timeout`
* `wait_flush_timeout`

Or something more like a wrapper struct that adds the timeout? This can be done in client code but it's a bit unwieldy with having to provide your own semi-redundant `Unpark` impl.

**Comment by alexcrichton** [comment]
I think in the long run these are just going to be conveniences for what you can build externally, so I'm not too too worried about ergonomics here (they're already pretty bad with `Spawn`). 

In that sense I think basically adding `_timeout` methods is fine.

**Comment by abonander** [comment]
@alexcrichton One concern with having the timeout methods meant to be called in a loop from the outside is that the `Arc<Unpark>` that they use will be getting repeatedly allocated and deallocated. There's not really a good way around this with the current design; exposing it to the user so they can hang onto it is little more gain than having them create this abstraction themselves.

I'm playing around with the idea of having a `WithTimeout` adapter, though, which gives us a little more flexibility. We can keep the `Arc<Unpark>` and potentially the timeout in the adapter while not making `Spawn` itself any bigger. It could also be generic over `BorrowMut<Spawn<_>>` so it can take ownership or mutably borrow.

There is an issue with it being sent across threads as it'll retain the wrong thread token to unpark, though this could be remedied by replacing the thread token if necessary--we can check equality by comparing the raw thread handles. Alternately, we could just opt-out of `Send` for the `WithTimeout` adapter, though it's not strictly necessary for thread safety.

**Comment by carllerche** [comment]
Why not take `&Arc<Unpark>` instead?

**Comment by abonander** [comment]
Most of the point of this was to avoid the user having to create their own `Unpark` impl which is redundant to the private one in the module. Otherwise there's no point over the user creating their own abstraction.

**Comment by alexcrichton** [comment]
So one thing I'm not sure about is how this'll interact with various executors. Does the desire for timeouts only arise from blocking on futures? Or also during the execution of a future in a typical setting?

If it's only related to blocking on futures then we may wish to adapt `Stream::wait` and `Sink::wait` return values to have a configurable timeout. We could then add something like a `Future::waiting` method which returns an adapter which has a configurable timeout. (or something like that).

Does that make sense?

**Comment by abonander** [comment]
> Does the desire for timeouts only arise from blocking on futures? Or also during the execution of a future in a typical setting?

For my use-case, I want the future to be re-polled even if it can't move forward. While futures *should* support being re-polled even if they can't move forward (they have to when working with `Spawn::wait_*()` since parked threads can wake spuriously), I don't know your opinion on whether or not they should be allowed to *assume* they'd be re-polled on a regular basis, since that does imply some coupling between the future and the executor. I mentioned my use-case in the OP--for that, coupling is fine because it's all in the same file anyway.

> If it's only related to [...]. Does that make sense?

It does, and that would work for my use-case, but since these methods already delegate to `Spawn`, what's the point in having a high-level abstraction without exposing the underlying mechanism? Both would be preferable, I think.

**Comment by carllerche** [comment]
@abonander I agree that there should be a way to poll a future off task w/o passing an unpark handle, but I don't think `Spawn` would be the place to do that. I haven't put much thought in trying to figure it out though.

**Comment by abonander** [comment]
That was my point in suggesting an adapter/wrapper for `Spawn` that holds the `Unpark` and can take timeouts. 

Alternately, though this perhaps isn't that good of an idea, we can expose the `ThreadUnpark` type that `Spawn` uses, maybe hiding the `thread::current()` in the constructor and also providing a constructor that directly returns an `Arc` just for a little more convenience. Then the solution to the timeout issue is as simple as adding a `park_timeout()` method. 

A potential issue, like with the previously suggested wrapper type, is that the user could move it to a different thread and then end up with a deadlock because the unparks are being sent to the wrong thread handle. We can't opt-out of `Send` here because it's required by `Unpark`, though. I don't think it's that big of an issue, a documentation warning should suffice, or maybe an assert in the parking methods that check that the stored thread handle is the current thread.

**Comment by alexcrichton** [comment]
Ah yeah so I would imagine that if a future wants to be polled on a regular interval it would internally use a future to schedule such a notification, not relying on the executor (in the general abstract sense). This makes sense from an implementation perspective but not necessarily a compositional perspective I think?

**Comment by abonander** [comment]
That works, and it's pretty much already been done in a third-party crate, but the issue is that it requires an extra thread to send the notification, or an OS message loop to use a timer primitive.

So unless you want to introduce an interface for a future to ask to be polled again on a timeout--which may not be a bad idea but may be complicated to implement and not supported by all event loops so it would need some kind of fallback--then supporting it in `Spawn` is probably the better way anyway, even if it's at the wrong level conceptually. 

What do you think of just exposing `ThreadUnpark` to provide a basic `Unpark` impl to client code, and adding a `park_timeout()` method? It would save some boilerplate for users that want to do their own thing with `Spawn`.

**Comment by abonander** [comment]
I've now realized that `tokio-core` basically has everything I want already, but I'd consider it pretty heavyweight for my use case since I'm not doing anything with evented I/O.

**Comment by alexcrichton** [comment]
@abonander oh right yeah I wouldn't want this to *require* an extra thread, but I'd imagine that the support could be implemented in the same fashion that tokio-core does today (just without I/O). Put another way I'd imagine that most executors would provide the ability to have some form of timeout, it's just that the source of the timeout may vary across exeuctors. 

We could expose `ThreadUnpark` yeah, but I fear that it wouldn't solve much of the problem here. Once you reach down into the `futures::executor` module you're already pretty much in the weeds and I'd imagine that not having to reimplement `ThreadUnpark` would be the least of your worries :(

**Comment by abonander** [comment]
So are you thinking something more like lifting the timeout support from tokio-core itself? That could be an option.

**Comment by alexcrichton** [comment]
Yeah so I've recently wanted to be able to do that in the `futures` crate itself. Basically support the `Timeout` and `Interval` types in `futuers` instead of `tokio-core`. That implies, however, that all executors are able to support timeouts, which is not required of executors today. As a result I think it'd be a breaking change, so I haven't thought through it too much.

In general though, yes. I'd expect this problem to be solved with types like `Timeout` and `Interval`, regardless of whether they come from tokio-core or another executor.

**Comment by abonander** [comment]
Okay, closing this then if you'd prefer to go in that sort-of direction for this use case.

**Comment by alexcrichton** [comment]
Ok. If that ends up being too onerous to implement or doesn't work well locally, I don't mind revisiting this!

**Pull request closed without merging**
