### PR TITLE
UnboundedSender::send does not need to accept mut self

### PR DESCRIPTION
**Pull request by stepancheg**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can the duplication of `do_send_nb` be avoided?

I'm not entirely sure I'd like to change this just yet as leaving it with `mut` reserves the right to modify the implementation in the future, but I don't have a concrete idea in mind of how we'd exercise that.

**Comment by stepancheg** [comment]
`UnboundedSender` is both `Send` and `Sync`, it can be safely shared between threads (e. g. placed in `Arc`). I think that's convenient.

Extracted a bit of code into `queue_push_and_signal` function, but I'm not sure it got better.

Also patched `stress_shared_unbounded` test to use `UnboundedSender::send` instead of `Sink::send`.

**Comment by alexcrichton** [comment]
Yes I can see how it's convenient, but it's strictly less flexible. I'm not sure if I'm willing to give up that flexibility just yet.

**Comment by alexcrichton** [comment]
Hm ok in retrospect it seems like almost a waste to not expose this. The only optimization I can think of is that of like the standard library where internally the channel is "upgraded" over time. I'd almost prefer that if we ever did something like that it's done out of tree, not here, so in that sense I'd be ok implementing this change.

@aturon or @carllerche, any last-minute thoughts on this?

Note that we'd probably want to accompany this with `Sink for &'a {UnboundedSender, Sender}` as well to emphasize that you only need a shared reference for those implementations.

**Comment by carllerche** [comment]
The implementation of the mpsc channel originally came from [here](https://github.com/carllerche/futures-mpsc).

We could continue the experimentation there.

**Pull request merged**
