### PR TITLE
Update documentation for flatten

### PR DESCRIPTION
**Pull request by Idolf**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Perhaps this could be changed to say "roughly equivalent"? I like the brevity of just using `then`, and I feel like being 100% correct is why the combinator exists and we perhaps don't need to spell it out in the docs.

**Comment by Idolf** [comment]
Perhaps I am misunderstanding something, but `self.then(|x| x)` does not typecheck in my head, nor can I get a variation of it to typecheck in my test program.

Perhaps you meant "roughly equivalent to `self.and_then(|x| x)`? I actually considered writing something along those lines initially.

**Comment by alexcrichton** [comment]
Oh hm yes I think you're right! I do think this is more equivalent to `and_then(|x| x)`

**Comment by Idolf** [comment]
PR updated!

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
