### PR TITLE
Use `debug_assert` for invariants.

### PR DESCRIPTION
**Pull request by leodasvacas**
Particularly in `Stream` combinators.

### CODE REVIEW

**Comment by NeoLegends** [comment]
I'm not sure this is the right approach. Lowering asserts to debug-only reduces the guarantees / invariants for release code.

**Comment by alexcrichton** [comment]
Did you find that this came up in profiles in release code?

**Comment by leodasvacas** [comment]
@alexcrichton No, this is just speculation, it seems difficult to make this show up in a benchmark.

**Comment by alexcrichton** [comment]
Ok, in that case I'm going to close as I'd prefer to not move these to debug asserts, but if they show up in profiles please let me know!

**Pull request closed without merging**
