### PR TITLE
Remove slot abstraction as it deemed uncertain

### PR DESCRIPTION
**Pull request by tailhook**
Closes #604, #586. Reverts #570, #585 (note it reverts rust version to 1.13.0 too)

Okay, I'm not sure if my argumentation was strong enough in #604, but let's remove it so we don't have to block a release anymore.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks @tailhook! Sorry for being a little slow to reply on these, I've been pretty busy lately :(

**Comment by carllerche** [comment]
@tailhook Do you plan on creating this in a repo as I think that I'd be interested in using it personally :)

**Comment by tailhook** [comment]
@carllerche Yes. Just released [async-slot](https://crates.io/crates/async-slot) crate.

**Comment by carllerche** [comment]
Thanks, I actually realized what I need is multi consumer. So I will try implementing something for that.

**Comment by carllerche** [comment]
I pushed my code here: [futures-watch](https://github.com/carllerche/better-future/tree/master/futures-watch).

**Pull request merged**
