### PR TITLE
replace try! macro with ?

### PR DESCRIPTION
**Pull request by cssivision**

### CODE REVIEW

**Comment by cssivision** [comment]
fix https://github.com/alexcrichton/futures-rs/issues/563

**Comment by alexcrichton** [comment]
Thanks! Can you update the minimum version on CI?

**Comment by cssivision** [comment]
yes, but which version should be?

**Comment by alexcrichton** [comment]
The version of rust that added `?`

**Comment by cssivision** [comment]
yes, the minimum version that add `?`

**Comment by alexcrichton** [comment]
The process you would go through to figure that out is the same that I'd do

**Comment by cssivision** [comment]
ok, i will fix this.

**Comment by cssivision** [comment]
it, 1.13.0, i found it in the [release page](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1130-2016-11-10).

**Pull request merged**
