### PR TITLE
add Stream::concat

### PR DESCRIPTION
**Pull request by seanmonstar**
A possible solution to #390. Another name I considered was `extend`, but maybe that could be confused with some how extending the actual stream.

### CODE REVIEW

**Comment by carllerche** [comment]
Given that the container is provided, I would suggest that `extend` is not the correct fn name.

It seems that this could be better functionality provided as a separate function? Something like:

```rust
future::extend(my_buffer, my_stream) -> impl Future<Item = MyBuffer>`
```

**Comment by alexcrichton** [comment]
Yeah I'm not totally sure on the naming here, I typically expect "concatenate" to not take a buffer as an argument and maybe even take a separator, but it does neither here! I sorta like the name 'extend' actually as you're extending a provided buffer.

@carllerche I'd prefer a trait method for this as it's a bit more ergonomic to call (one less import), but do you think it fits more with the other free-function combinators that we have?

**Comment by carllerche** [comment]
I generally prefer mirroring std as much as possible. In this case, the goal is to provide an equivalent to the Extend trait for futures. That would mean creating a new trait: FutureExtend or something like that. 

I also prefer to not use a few traits (Future, Stream) as essentially a flat namespace for all functions. It hurts discoverability. 

I do think that before commiting to an API it would be worth exploring how specialization could potentially handle the case of the Stream of bytes knowing the final lengh.

**Comment by alexcrichton** [comment]
@carllerche I'm not sure I follow the point about `FutureExtend`? With this use case at least it seems like there's not much of a use case for appending an element to a collection taking a long time (e.g. needing to itself return a future). I'd imagine that `Extend` (or some similar trait) ends up being fine in this case.

I agree that a flat namespace isn't great, but we also don't want to leave useful functionality for everyone to pull in an extra crate, so we need to make sure we've at least got the essentials in this crate.

**Comment by seanmonstar** [comment]
As for the name `concat`, it came to mind because of my JavaScript background, where `Array.concat` takes any number of arrays and concatenates them all into a single array: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

I can see `stream.extend(vec)` making sense, but I can also see someone reading it like `stream.extend(other_stream)` (if they hadn't checked the docs).

As for the failing tests, I noticed that `catch_unwind` was failing for me locally on nightly also. I haven't looked to see if this was a bug in nightly, or if futures needs to be updated.

**Comment by carllerche** [comment]
After re-reading, I think that I am (mostly) happy w/ the PR. Maybe, the one thing I would suggest is since this is `concat`, to not pass in an argument and instead, extend onto the first value returned by the stream.

I *believe* that the `Concat` type could, in the future, be specialized to be smart and `reserve` the amount of space necessary if the stream can provide that info. For example a HTTP body stream impl could specialize the `Future::poll` implementation and reserve the amount of space specified by content-length.

So, given all that, w/ the change I suggested above, I'm 👍 

@alexcrichton Re my comment about `Extend`, it isn't actually applicable to this specific case because this is a "flat extend" (concat). (I was misunderstanding).

However, to elaborate. [`Extend`](https://doc.rust-lang.org/std/iter/trait.Extend.html) takes an `Iterator`. Given that `Stream` is the async version of `Iterator`, `FutureExtend` would take a stream, and extend self w/ the received values. It needs to be "async" since values are received from the stream "async".

**Comment by seanmonstar** [comment]
I want to make the changes needed to get this done, but I admit I'm not sure what exactly they are. Sounds like Alex prefers `Extend`, Carl prefers `Concat`.

Additionally, there's a suggestion to not provide a target to fill up, but to make use of the first item in the stream. This could allow something neat, like if it is a `Stream` of `Bytes`, the `Bytes` could maybe just expand its length instead of copying the other `Bytes`. However, providing the target directly allows someone to `reserve` beforehand the size they expect (which is usually pretty easy to know in something like HTTP, by checking the `Content-Length` header first).

**Comment by alexcrichton** [comment]
Oh I don't feel too strongly about `Extend`, `Concat` I could live with. @carllerche how do you feel about taking in an argument to do optional reservation if necessary?

**Comment by carllerche** [comment]
If `concat` uses the first item, reservation could be done w/ `chain`:

```rust
let body = BytesMut::with_capacity(content_length)
   .chain(body_stream)
   .concat();
```

Reservation could also be done in the future w/ specialization.

Given those two options, I would opt for the more ergonomic API: not taking an argument.

**Comment by seanmonstar** [comment]
Updated to make use of the first item from the stream, so it looks like `let body = stream.concat()`.

**Comment by carllerche** [comment]
Seems good to me.

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
