### PR TITLE
Fold for list of futures

### PR DESCRIPTION
**Pull request by weiznich**
* implement an ordered and an unordered variant

Basically what I wanted to do in #202.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder if this could perhaps be a more ergonomic conversion from a list of futures to a stream? That way you could leverage the standard `fold` and `buffer_unordered` combinators

**Comment by weiznich** [comment]
You are thinking about something like this?

```rust
    let data = (0..MAX).rev().collect::<Vec<_>>();
    ::futures::stream::iter(data.clone().into_iter().map(Ok))
          .map(|d| pool.spawn_fn(move || work(d as u32)))
          .buffer_unordered(MAX)
          .fold(0, |acc, a| Ok(fold(acc, a)))
          .wait()
          .unwrap()
```

I'm not sure if this really serves the problem I'm trying to solve. `buffer_unorderd` takes a (ordered) Stream of values which could be evaluated as futures, caches some of those futures and then waits till them are finished. In my usecase I've a list of a possible large number of futures which are started nearly at the same time and which should be evaluated in parallel. Each future reads the content of an file. If an future has finished the content  from those file could be merged into the final result using the fold method. (The order of merging does not matter here.) Using the fold_unorderd method from this pull-requst gives me on my benchmarks a performance improvement of ~3-4% to a plain `::futures::collect(future_list).into_iter().fold(init, fold_function)`. 
I will also try to test the stream approach from above in the next few days.

**Comment by alexcrichton** [comment]
Yeah that's along the lines of what I was thinking in that the implementation of this sort of feature would basically compile down to those operations. If that sequence of operations is too slow, however, I'd love to dig into why and see if there's something we can improve!

Another possibility here is to provide an ergonomic conversion from a list of futures to a stream, basically automating the first steps in the gist:

```rust
    let data = (0..MAX).rev().collect::<Vec<_>>();
    ::futures::stream::iter(data.clone().into_iter().map(Ok))
          .map(|d| pool.spawn_fn(move || work(d as u32)))
          .buffer_unordered(MAX)
```

as just:

```rust
let stream = stream::futures(data);
```

Once you've done that it's just a standard `Stream::fold` away to get the same result as before.

I'd basically just prefer to push as hard as we can on the future/stream combinators (and primitives) before we add similar functionality in a specialized fashion. Having to understand fewer things is always nicer!

**Comment by weiznich** [comment]
Closed in favour of #263

**Pull request closed without merging**
