### PR TITLE
docs: Document the slot module

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
@alexcrichton I'm super excited about this library and have been reading through. I found parts of `Slot` hard to grasp, particularly cancellation, and ended up documenting it. I'm doing the same with other parts as I read through. Let me know if you want other PRs!

**Comment by kamalmarhubi** [comment]
I also added a couple of TODOs that look like things that could make sense. Happy to actually do those if they do make sense.

**Comment by alexcrichton** [comment]
Thanks! This library is currently **seriously** under-documented, and I've got a huge amount of documentation I'd want to add. The implementation of `Slot` is massively tricky and isn't really currently intended for anyone to read but me, unfortunately. Once this starts getting further along I'll be sure to add them plus many more!

**Comment by kamalmarhubi** [comment]
Yeah I figured it might be in too early a state for PRs. FWIW, I'll continue adding docs in my [doc branch](https://github.com/kamalmarhubi/futures-rs/tree/doc) as I get more understanding of how this fits together, and how to use it. Also some experiments in other branches, eg [a basic http multiplexer](https://github.com/kamalmarhubi/futures-rs/tree/http-mux) and [a threadpool-based executor for fs operations](https://github.com/kamalmarhubi/futures-rs/tree/thread-pool-io) so far.

**Comment by kamalmarhubi** [comment]
Also consider this an offer to write some docs :-)

**Comment by alexcrichton** [comment]
Nice! We talked last night, but I'll try to prioritize soon to write docs for all this stuff as well, especially the particularly tricky parts.

**Pull request merged**
