### PR TITLE
convert Run to Notify API

### PR DESCRIPTION
**Pull request by stbuehler**
`Run` (created by `Spawn::execute`) still used the deprecated `Unpark` API; use `Notify` instead. (`Run` and friends are still required by `futures-cpupool`, so they probably shouldn't be marked deprecated just yet).

After this no public non-deprecated feature uses deprecated features, and the second commit will add `#[cfg(feature = "with-deprecated")]` to all `deprecated` and `allow(deprecated)`  items.

Without `with-deprecated` it will always use the stub `UnparkEvents` and `BorrowedEvents` from the `core` implementation.

This should improve benchmarks without `with-deprecated` overall, but `unbounded_uncontended` and `thread_yield_multi_thread` seem to get slower by this...

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! The `with-deprecated` feature though was sort of a hack added awhile back which we unfortunately can't actually expand like this in a backwards compatible fashion. For example if a crate disabled default features and then didn't enable `with-deprecated` this commit could run the risk of "deleting" used apis for that crate.

Could this for now just include the `execute` changes? We can hopefully eventually just remove the `with-deprecated` business entirely!

**Comment by stbuehler** [comment]
Right, I see.  So there could theoretically be a feature the other way round (`disable-deprecated`) which one would have to enable manually, instead of one enabled by default. I still think this would be nice to have :)

But I'll remove the second commit from this PR, and we can discuss in a new one.

**Comment by alexcrichton** [comment]
Ok that sounds fine by me. I'm not sure I'd like to stick with the `with-deprecated` (or `disable-deprecated`) business though as it's typically only temporarily useful but can be a big burden to maintain over time (huge `#[cfg]` explosion)

**Comment by stbuehler** [comment]
Removed the commit with the changes to `with-deprecated`.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
