### PR TITLE
Add with_flat_map sink combinator

### PR DESCRIPTION
**Pull request by exrook**
Add a `with_flat_map` combinator to `Sink`, similar to `flat_map` from `std::Iterator`

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder though, would this perhaps be better to return a stream rather than an iterator?

**Comment by exrook** [comment]
That's probably a better idea, I only used iterator because I wasn't sure how to implement it with Stream. I'll see if I can figure it out sometime this week.

**Comment by exrook** [comment]
I found the time to rewrite this patch to work with Streams rather than iterators. Let me know if you have any other suggestions.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
