### PR TITLE
Implement Stream for Empty

### LINKED ISSUE #113: Implement Stream for Empty
Tokio has a use case for Empty with Stream:

https://github.com/tokio-rs/tokio-line/blob/master/src/empty.rs

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Closes #113

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! It seems reasonable to me to reuse the type here, but to reduce the surprise factor could you also add this to `src/stream/mod.rs`?

```rust
pub use empty::{Empty, empty};
```

That is, we in theory also want `futures::stream::{empty, Empty}`, but it's fine if it ends up returning the same underlying type itself.

**Comment by alexcrichton** [comment]
Although conversely this would be a bit of a departure from the existing conventions of the futures/streams section being pretty separated. One example issue that could arise is that now `empty().poll()` requires UFCS to disambiguate because it wouldn't be sure if you're calling `Future::poll` or `Stream::poll`. 

Perhaps this could add a new `src/stream/empty.rs` instead in that case?

**Comment by nabijaczleweli** [comment]
I've made it so `stream::Empty` is a `Stream` (with impl as suggested in #113) and `stream::empty()` to create it.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
