### PR TITLE
futures-mio: update comment and simplify echo example

### PR DESCRIPTION
**Pull request by dwrensha**
Removes an obsolete comment about `Arc` and simplifies some code.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I think the `lazy` is still needed though to ensure that the `TaskData` is associated with the correct task though? (we're spawning a new task for each connection).

**Comment by dwrensha** [comment]
Yeah, I'm confused about that! It seems to work fine without the `lazy` on OSX.  But just now I've just tested it on Linux and there it hits the panic described in #70.

**Comment by alexcrichton** [comment]
Interesting! This definitely shouldn't encounter any form of platform-specific behavior. I ran it locally on OSX and it seems to panic, though. I wonder if may be the OSX/Linux versions you're testing may accidentally be different?

**Comment by dwrensha** [comment]
Ah, no, sorry. My problem was apparently that I misunderstood how cargo workspaces work. Now I'm seeing the error in both places.

**Comment by dwrensha** [comment]
Ok, now, this PR just updates the comment about `Arc`.

**Pull request merged**
